### ISSUE TITLE
Install fails

### ISSUE THREAD

**Issue by mfauvain** [jamespfennell/transiter-nycsubway#1]
Hi, I tried to install us-ny-subway as per git page, with no luck. 
```
"id": "us-ny-subway",
    "status": "INSTALL_FAILED",
    "name": "New York City Subway",
    "href": "http://localhost:8000/systems/us-ny-subway"
```
when installing I initially see:
```
{
  "id": "6",
  "status": "SCHEDULED",
  "stack_trace": null,
  "scheduled_at": 1662936034.96803,
  "completed_at": null,
  "system": {
    "id": "us-ny-subway",
    "status": "SCHEDULED",
    "name": "(Awaiting install for full name)",
    "href": "http://localhost:8000/systems/us-ny-subway"
  }
```

Can you help?

**Comment by mfauvain** [comment]
Scratch that.. did not read `it must be installed in all containers ` ... my bad.

**Comment by jamespfennell** [comment]
Yeah this is a total footgun with the current architecture of Transiter. I hit it so many times when restarting my own Transiter instances - I forget to install the Python package, and then stuff just breaks.

I've been recently working on a new version of Transiter that doesn't have this issue. Instead, all of the parsers for the NYC subway are just bundled with the main package.
